name: Run fetch.py on Commit

on:
  push:
    branches: [ main, master ]
    
jobs:
  run-fetch:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - run: | 
        curl --header "authorization: token "$VH_API_TOKEN https://app.valohai.com/api/v0/projects 
        echo "Done ?"
