name: Run fetch.py on Commit

on:
  push:
    branches: [ main ]
    
jobs:
  run-fetch:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - run: python valohai-tech-action/fetch.py
