
name: Run fetch.py on Commit

on:
	push:
		branches: [ main, master ]
    
jobs:
	run-fetch:
		runs-on: ubuntu-latest

		steps:
		- uses: actions/checkout@v4
		- uses: actions/setup-python@v5
			with:
				python-version: '3.11'

		- name: install-dependencies
			run: |
				python -m pip install --upgrade pip 
				pip install requests

		- name: run-fetch
			env: 
				VH_API_TOKEN: ${{ secrets.VH_API_TOKEN }}
			run: python valohai-fetch-action/fetch.py
